[package]
name = "gnosis-primitives"
version = "0.2.5"
edition = "2024"

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v2.3.0" }
reth-db = { git = "https://github.com/paradigmxyz/reth", tag = "v2.3.0" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v2.3.0" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v2.3.0" }
reth-cli-commands = { git = "https://github.com/paradigmxyz/reth", tag = "v2.3.0" }

# Independent crates
reth-codecs = { version = "0.4.1", default-features = false }
reth-primitives-traits = { version = "0.4.1", default-features = false }

alloy-primitives = { version = "1.6.0", default-features = false }

alloy-consensus = { version = "2.0.5", default-features = false }
alloy-eips = { version = "2.0.5", default-features = false }
alloy-serde = { version = "2.0.5", default-features = false }

alloy-rpc-types = { version = "2.0.5", features = ["eth"], default-features = false }
alloy-rlp = { version = "0.3.13", default-features = false }

serde = { version = "1.0", features = ["derive"], default-features = false }
derive_more = { version = "2", default-features = false, features = ["full"] }

alloy-trie = { version = "0.9.4", features = ["ethereum"] }
serde_with = "3"
test-fuzz = { version = "7" }
modular-bitfield = { version = "0.13.1" }

[dependencies.criterion]
version = "0.5"
features = ["html_reports"]
optional = true


[features]
default = []
bench = ["criterion"]

[[bench]]
name = "header_performance"
harness = false
required-features = ["bench"]
